### ISSUE TITLE
Building as a dependency to other CMake project

### ISSUE THREAD

**Issue by exuvo** [Noxagonal/Vulkan2DRenderer#112]
I would like to build this as a dependancy to my project but your CMakeLists refers to the root project all the time.

Changes needed:
Replace CMAKE_SOURCE_DIR with PROJECT_SOURCE_DIR,
CMAKE_BINARY_DIR with PROJECT_BINARY_DIR.

This makes all your paths relative to your project and not the top level project (which are the same if you just build VK2D but different if my project has VK2D as a dependency).

I can make a pull request if that would be easier for you.

**Comment by Noxagonal** [comment]
Hey, sorry for the long wait. Yeah that sounds good. I could grab from your branch if that's okay?

**Comment by exuvo** [comment]
This https://github.com/exuvo/Vulkan2DRenderer/tree/20925688b3b11d385858f66675fd486b818d7016 tree should be good for just the changes to build this as a nested project.

We also did some reformatting of includes to be relative to the Source and Include directories instead of having to use ../../ all the time. That can be found in this tree https://github.com/exuvo/Vulkan2DRenderer/tree/302e62c7d97f8c65e9f935af3c29e9e52ec0abeb . My IDE eclipse handles this just fine but maybe check if yours does too.

A note about your usage of M_PI, many c libs already define it in math.h so we on linux were getting errors where you declare it yourself as a variable (ie it becomes double 3.14 = 3.14; error identifier expected). Doing it as a ifndef define should work better but we just commented it out for now when we tested. If you are okay with using c++20 they have added it there under std::numbers::pi (took them long enough).

The tests seems to work well on linux btw.

**Comment by Noxagonal** [comment]
I looked over the differences and I like most of those changes, I'll update my branch sometime soon and see what I could pull from your branch.

There's vk2d::PI (I'll move it to a better location soon), forgot to remove the M_PI.
I want to conform to C++17 for the time being, but yeah, I agree it took them long enough. XD

The API is still changing a bit from time to time, just so that you're aware, I haven't locked anything down yet. I'll rewrite the tests whenever I have a better picture of how the final API will look like but it's good to know they pass on Linux as well. 👍

**Comment by exuvo** [comment]
Thats nice to hear.

I'm fine with API changes, my game rendering is mostly solitary white pixels and some circles so it should be easy to adapt.

**Comment by Noxagonal** [comment]
I reviewed and applied most changes from your fork to mine. If you have time, could you test the "dev" branch and let me know if it works before I merge it to master?

**Comment by exuvo** [comment]
Gcc requires a parentheses around `unsigned int`in `glfw_gamma_ramp.size = unsigned int( glfw_ramp_node_count );` in Window.cpp:4273, other than that it builds and runs fine.

It seems my reasoning about the CMake sources was slightly flawed, it is enough with add_custom_command with output and depends for me. The if(MSVC) in CMakeLists:129 can be removed and leave just the version that includes FILES_SHADERS for add_library.
