### ISSUE TITLE
Stuck fence in vk2d::_internal::AquireImage after VK_ERROR_OUT_OF_DATE_KHR

### ISSUE THREAD

**Issue by exuvo** [Noxagonal/Vulkan2DRenderer#117]
When i resize a window i occasionally i get:
> Could not aquire image, out of date swapchain, recreate swapchain now.
> Begin recreating window resources.
> Done recreating window resources.

At this point the vkWaitForFences in Window.cpp:vk2d::_internal::AquireImage gets stuck. I changed the timeout on the vkWaitForFences to 1s (1000000000) to see it better while rendering a moving cube.

If i understand the code correctly the wait is not needed in that case as the newly created swapchain has never been used, so a return true after `if( !AquireImage(` might be the fix? Seems to work for me at least but i'm not well versed in vulkan.

https://github.com/exuvo/Vulkan2DRenderer/commit/b552227befeb4ef8c5b8a6f0765fb21aaa5ef373

Btw its spelled acquire not aquire.

**Comment by Noxagonal** [comment]
Swapchain images are owned by the OS, vkAcquireNextImageKHR returns a swapchain image index as soon as the OS presentation engine knows which one it will give us next, however it does not mean that image is immediately available to be written so we wait on the fence until it is.

I guess it was waiting on that fence twice in a row?
I'll have to rewrite that function with lambdas to make more sense anyways.

**Comment by exuvo** [comment]
Ah i did not realize it was calling it self again, yes it is waiting twice on the same fence, once in the recursive call and then again when it returns and continues down. So the return true is correct fix but for different reason.

**Comment by Noxagonal** [comment]
Looking back I honestly don't know what I was thinking when I wrote that function. XD
I'll rewrite it sometime soon.
