### ISSUE TITLE
EventWindowMaximize, You forgot to realize it

### ISSUE THREAD

**Issue by bizehao** [Noxagonal/Vulkan2DRenderer#165]
EventWindowMaximize Forgottened by you.

Window.cpp  namespace vk2d::_internal

`void glfwWindowMaximizeCallback(GLFWwindow* glfwWindow, int maximized);`

`void vk2d::_internal::glfwWindowMaximizeCallback(GLFWwindow* glfwWindow, int maximized){
	auto impl = reinterpret_cast<vk2d::_internal::WindowImpl*>(glfwGetWindowUserPointer(glfwWindow));

	if (maximized) {
		impl->is_maximized = true;
	}
	else {
		impl->is_maximized = false;
		impl->should_reconstruct = true;
	}
	if (impl->event_handler) {
		impl->event_handler->EventWindowMaximize(impl->my_interface, bool(maximized));
	}
}`

`glfwSetWindowMaximizeCallback(glfw_window, vk2d::_internal::glfwWindowMaximizeCallback);`

WindowImpl.h

`friend void glfwWindowMaximizeCallback(GLFWwindow* glfwWindow, int maximized);`

**Comment by bizehao** [comment]
Thank you for this works, I learned a lot!

**Comment by Noxagonal** [comment]
Sorry I haven't looked at this code for a while, I'm glad this has been useful to you.

Thanks for letting me know. Added maximize event handling to dev branch and will test properly later.
