### ISSUE TITLE
Add render targets.

### ISSUE THREAD

**Issue by Noxagonal** [Noxagonal/Vulkan2DRenderer#81]
Could use custom render targets. Render to target and use as a texture later. Window class would possibly have internal render target to draw to instead of directly rendering to the window surface. Render targets could also be blurred.

**Comment by Niko40** [comment]
This also enables multithreaded rendering to a custom render target... Not sure if this would be needed though.
Multithreading critical sector is considered to be all commands to a single render target, usually a window.

**Comment by Noxagonal** [comment]
Implemented basic render target textures.
